# Generated by Django 4.1.7 on 2023-03-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_note_note_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='note',
            name='transcript',
            field=models.TextField(default=''),
        ),
    ]
