# Generated by Django 4.1.7 on 2023-03-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_note_notes_alter_note_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_buffer',
            field=models.TextField(default=''),
        ),
    ]
